[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.97.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
dataset-dr = { path = "crates/dataset-dr" }
graph-dr = { path = "crates/graph-dr" }
iri-dr = { path = "crates/iri-dr" }
macro-enum-dr = { path = "crates/macro-enum-dr" }
macro-validated-dr = { path = "crates/macro-validated-dr" }
term-dr = { path = "crates/term-dr" }
oxiri = "0.3"
oxrdf = { version = "0.3", features = ["rdf-12"] }
paste = "1.0"
snafu = "0.8"
url = "2.5"
proptest = "1.0"
