[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.97.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rdf-trilith-dataset = { path = "crates/rdf-trilith-dataset" }
rdf-trilith-graph = { path = "crates/rdf-trilith-graph" }
rdf-trilith-iri = { path = "crates/rdf-trilith-iri" }
rdf-trilith-macro-enum = { path = "crates/rdf-trilith-macro-enum" }
rdf-trilith-macro-validated = { path = "crates/rdf-trilith-macro-validated" }
rdf-trilith-term = { path = "crates/rdf-trilith-term" }
oxiri = "0.3"
oxrdf = { version = "0.3", features = ["rdf-12"] }
paste = "1.0"
snafu = "0.8"
url = "2.5"
proptest = "1.0"
