[package]
name = "links-dr"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Link type system converting markdown links, wiki links, and autolinks into each other"
license.workspace = true

[dependencies]
iri-dr.workspace = true
macro-validated-dr.workspace = true
snafu.workspace = true
